version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/conf.py  # Update this path if your conf.py is elsewhere

python:
  install:
    - requirements: docs/requirements.txt

